### ISSUE TITLE
Publish the random filename generation as a separate package

### ISSUE THREAD

**Issue by papb** [fabiospampinato/atomically#4]
I am really interested in reusing your temporary file naming strategy for something else, and interestingly I found you even have a todo for that already:

https://github.com/fabiospampinato/atomically/blob/711df7c6092ad47edbb22d60bb71bb2393aabb1b/src/utils/temp.ts#L11

Do you plan on doing this in the near future? If not, can I do it (and put you as a maintainer if you wish)?

**Comment by fabiospampinato** [comment]
I won't be publishing that as a standalone package in the near future, if ever.

Feel free to extract that into your own package.
