### ISSUE TITLE
v2.0.0 changelog

### ISSUE THREAD

**Issue by RDIL** [fabiospampinato/atomically#6]
Hi!  Saw that v2.0.0 was officially released.  I wasn't able to find a changelog, so I was wondering what changes are required on the user-end for the update?

Thanks!

**Comment by fabiospampinato** [comment]
You can check the commits history (https://github.com/fabiospampinato/atomically/commits/master), the only potentially breaking change is that I switched to ESM. It probably doesn't actually change anything for most people.
